spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
     name: microservisecloud-config-atguigu-dev
---
spring:
  profiles: test
  application:
     name: microservisecloud-config-atguigu-test