spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
     name: microservisecloud-config-client
eureka:
  client:
    service-url:
      defualtZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
     name: microservisecloud-config-client
eureka:
  client:
    service-url:
      defualtZone: http://eureka-test.com:7001/eureka/